### PR TITLE
Fixing middleware docker image build

### PR DESCRIPTION
**Pull request by amendelzon**
- Fix middleware docker image build: installing an older Cython before the rest of the dependencies. This prevents some package builds from failing.

### CODE REVIEW

**Review by italo-sampaio — APPROVED** [review]
Looks good to me!

Just one side note: does it make sense to bump the version since we are not touching the firmware, just the build environment?

**Comment by amendelzon** [comment]
> Looks good to me!
> 
> Just one side note: does it make sense to bump the version since we are not touching the firmware, just the build environment?

That's a good question. We do want to avoid overwriting tags. What would be a good alternative?

**Comment by italo-sampaio** [comment]
> > Looks good to me!
> > Just one side note: does it make sense to bump the version since we are not touching the firmware, just the build environment?
> 
> That's a good question. We do want to avoid overwriting tags. What would be a good alternative?

Fair point on not overwriting tags. I also prefer the risk of adding too much information to the risk of having the same tag with two different meanings, so I would say let's merge it with the version bumping since it does no harm.

**Review by italo-sampaio — APPROVED** [review]
LTGM!

**Pull request merged**
